# Generated by Django 4.2.3 on 2023-07-22 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("popularity", models.IntegerField(verbose_name="Post popularity")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Creation time",
                    ),
                ),
                ("text", models.TextField(verbose_name="Post text")),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(max_length=100, verbose_name="Source name"),
                ),
                (
                    "subscribers",
                    models.ManyToManyField(
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subscribers to the source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Digest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posts",
                    models.ManyToManyField(
                        related_name="digests",
                        to="news.post",
                        verbose_name="Posts included in the digest",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Digest",
                    ),
                ),
            ],
        ),
    ]
