# Generated by Django 4.2.3 on 2023-07-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_post_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="news.source",
                verbose_name="News source",
            ),
        ),
    ]
