# Generated by Django 4.2.3 on 2023-07-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_subscription_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="parser_class",
            field=models.CharField(
                default="", max_length=100, verbose_name="Parser class for the source"
            ),
            preserve_default=False,
        ),
    ]
